FROM homeassistant/home-assistant:stable

RUN python3 -m pip install "goechargerv2==0.2.2"

COPY custom_components/go_echarger /config/custom_components/go_echarger
COPY configuration.dev.yaml /config/configuration.yaml
