FROM homeassistant/home-assistant:stable

RUN python3 -m pip install "smart-energy.goecharger-api==0.3.1"

COPY custom_components/smartenergy_goecharger /config/custom_components/smartenergy_goecharger
COPY configuration.dev.yaml /config/configuration.yaml
