FROM homeassistant/home-assistant:stable

RUN python3 -m pip install "smart-energy.goecharger-api==0.3.0"

COPY custom_components/smart_energy_goecharger /config/custom_components/smart_energy_goecharger
COPY configuration.dev.yaml /config/configuration.yaml
