"""Constants re-used across different files"""

DOMAIN = "go_echarger"
CONF_CHARGERS = "chargers"
ENABLED = "enabled"
CHARGER_ACCESS = "charger_access"
CHARGERS_API = "chargers_api"
API = "api"
INIT_STATE = "init"
UNSUB_OPTIONS_UPDATE_LISTENER = "unsub_options_update_listener"
MANUFACTURER = "go-e GmbH"
